name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ShravaniAnilPatil
          outputs: dist/snake.svg

      - name: Upload the Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
